import {format} from '../src/lib/8a';

const INPUT = {
  "zlaggableName": "Into the Light",
  "zlaggableSlug": "into-the-light",
  "cragSlug": "cat-slab-boulders",
  "cragName": "Cat Slab Boulders",
  "countrySlug": "united-states",
  "countryName": "United States",
  "areaSlug": "clear-creek-canyon-co",
  "areaName": "Clear Creek Canyon (CO)",
  "sectorSlug": "unknown-sector",
  "sectorName": "Unknown Sector",
  "category": 1,
  "difficulty": "7A+",
  "gradeIndex": 24,
  "totalAscents": 56,
  "totalRecommendedRate": 0.08928572,
  "averageRating": 3.4242,
  "flashOnsightRate": 0.232142866,
  "userClimbed": false,
  "userClimbedInfo": null,
  "hasVlId": false,
  "details": {
    "zlaggableName": "Into the Light",
    "zlaggableSlug": "into-the-light",
    "cragSlug": "cat-slab-boulders",
    "cragName": "Cat Slab Boulders",
    "countrySlug": "united-states",
    "countryName": "United States",
    "sectorSlug": "unknown-sector",
    "sectorName": "Unknown Sector",
    "category": 1,
    "difficulty": "7A+",
    "areaSlug": "clear-creek-canyon-co",
    "areaName": "Clear Creek Canyon (CO)",
    "averageRating": 3.4242,
    "totalAscents": 56,
    "onsightRate": 0.0178571437,
    "totalRecommended": 5,
    "season": [
      5,
      3,
      8,
      4,
      11,
      4,
      0,
      2,
      2,
      8,
      4,
      5
    ],
    "gradeIndex": 24,
    "grades": {
      "23": 1,
      "24": 55
    },
    "totalRedpoint": 43,
    "totalOnsight": 1,
    "totalFlash": 12,
    "totalGo": 0,
    "totalTopRope": 0,
    "totalFollowers": 0
  },
  "ascents": [
    {
      "userAvatar": "gallery/59130.jpg",
      "userName": "will castelli",
      "userSlug": "will-castelli",
      "date": "2021-02-07T12:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "f",
      "comment": "",
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Jackson Kohn",
      "userSlug": "jackson-kohn",
      "date": "2021-01-22T12:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "one of the best boulders ive done, hands down. really good movement traversing on crimps into an easy, juggy topout. ",
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Ross Cooper",
      "userSlug": "ross-cooper",
      "date": "2021-01-05T12:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "",
      "traditional": false,
      "project": false,
      "rating": 4,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": true,
      "isCrimpy": true,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Jacob Luciani",
      "userSlug": "jacob-luciani",
      "date": "2020-12-22T12:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "",
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "gallery/62164.jpg",
      "userName": "Jake Sugawara",
      "userSlug": "jake-sugawara",
      "date": "2020-12-20T12:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": true,
      "type": "rp",
      "comment": "",
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "p/gallery/how2oqiu.jpg",
      "userName": "Adam Block",
      "userSlug": "adam-block",
      "date": "2020-11-17T12:00:00+00:00",
      "difficulty": "7A",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "No one thinks this is soft?? Damn maybe this is just a Sport wankers delight. ",
      "traditional": false,
      "project": false,
      "rating": 4,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": true,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": true,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "p/gallery/fxsw3n0l.jpg",
      "userName": "Liz Haas",
      "userSlug": "liz-haas",
      "date": "2020-10-17T12:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "",
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Steve Mullins",
      "userSlug": "steve-mullins",
      "date": "2020-10-12T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "f",
      "comment": "",
      "traditional": false,
      "project": false,
      "rating": 4,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Jason Giblin",
      "userSlug": "jason-giblin",
      "date": "2020-10-08T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "1 session last year, 2 sessions this year. Thought I would get it first sesh this year, I didn't think I would fall on the ending but I did cause I didn't have a headlamp on and couldn't see the feet. Really good problem, I enjoyed this one a lot. Pretty stoked on my bouldering now",
      "traditional": false,
      "project": false,
      "rating": 5,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "PJ Rai",
      "userSlug": "pj-rai",
      "date": "2020-09-16T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "Stellar line! Nice after-work session with Mike on this rig. ",
      "traditional": false,
      "project": false,
      "rating": 5,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": true,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": true,
      "isCrimpy": true,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "gallery/31417.jpg",
      "userName": "Christophe Paquot",
      "userSlug": "christophe-paquot",
      "date": "2020-09-11T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "",
      "traditional": false,
      "project": false,
      "rating": 5,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Ron Johnson",
      "userSlug": "ron-johnson",
      "date": "2020-08-16T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": true,
      "type": "os",
      "comment": "Bitchin'",
      "traditional": false,
      "project": false,
      "rating": 3,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": true,
      "isCrimpy": true,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "gallery/34671.jpg",
      "userName": "K Boyko",
      "userSlug": "thundercling",
      "date": "2020-06-21T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "",
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": true,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Brent de Lara",
      "userSlug": "brent-de-lara",
      "date": "2020-06-13T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "not a single move above 6c/v5, but super fun all throughout",
      "traditional": false,
      "project": false,
      "rating": 4,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": true,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Zach White",
      "userSlug": "zach-white-tyyu1",
      "date": "2020-05-06T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "no PE",
      "traditional": false,
      "project": false,
      "rating": 3,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": true,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": true,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": true,
      "isCrimpy": true,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Ryan Anderson",
      "userSlug": "ryan-anderson",
      "date": "2020-04-27T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "f",
      "comment": "Cool power endurance traverse on some nice edges",
      "traditional": false,
      "project": false,
      "rating": 3,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Michelle Skuba Gray",
      "userSlug": "michelle-skuba-gray-a6ays",
      "date": "2020-04-19T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "Twas bright... in the light",
      "traditional": false,
      "project": false,
      "rating": 3,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Austin Purdy",
      "userSlug": "austin-purdy",
      "date": "2020-03-23T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "f",
      "comment": null,
      "traditional": false,
      "project": false,
      "rating": 3,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "F Mage",
      "userSlug": "f-mage",
      "date": "2020-03-14T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": null,
      "traditional": false,
      "project": false,
      "rating": 3,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Caitlin Maloney",
      "userSlug": "caitlin-maloney",
      "date": "2020-03-07T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "Finally got a peek at clear creek! Not a bad boulder to introduce the area. The V0 is suuuuuch a noice warm up.",
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Joaq ing",
      "userSlug": "joaq-ing",
      "date": "2020-02-29T12:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": true,
      "type": "rp",
      "comment": "Thought I climbed this in October 2019 but it turned out I exited early. A really fun line.",
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Scott Curtis",
      "userSlug": "scott-curtis",
      "date": "2020-02-29T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "Not one for traverses but this was stellar. Heel hook to crimpz.",
      "traditional": false,
      "project": false,
      "rating": 1,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": true,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Blair Seidlitz",
      "userSlug": "blair-seidlitz",
      "date": "2020-01-30T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "Really good except for chaos.  Really good power endurance with fun moves on kinda sharp holds.",
      "traditional": false,
      "project": false,
      "rating": 3,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "gallery/46498.jpg",
      "userName": "Dylan Connole",
      "userSlug": "dylan-connole",
      "date": "2020-01-03T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "Bah, blew the flash because i used the wrong heel. Hands soo numb",
      "traditional": false,
      "project": false,
      "rating": 3,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": true,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "jake michelotti",
      "userSlug": "jake-michelotti",
      "date": "2019-12-25T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "",
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "gallery/22751.jpg",
      "userName": "kenyon smith",
      "userSlug": "kenyon-smith",
      "date": "2019-11-15T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": null,
      "traditional": false,
      "project": false,
      "rating": 3,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Brennen Bull",
      "userSlug": "brennen-bull",
      "date": "2019-10-20T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "f",
      "comment": "Pretty good flow on this one, despite getting blasted by 40mph winds. Fuggin cold with that wind chill.",
      "traditional": false,
      "project": false,
      "rating": 3,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "",
      "userName": "Anonymous",
      "userSlug": "",
      "date": "2019-10-15T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": true,
      "type": "f",
      "comment": "",
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": true,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "gallery/49699.jpg",
      "userName": "Double Delay",
      "userSlug": "double-delay",
      "date": "2019-10-14T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": true,
      "type": "f",
      "comment": "about to hit CCC hard",
      "traditional": false,
      "project": false,
      "rating": 3,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Kyle Wagner",
      "userSlug": "kyle-wagner",
      "date": "2019-10-13T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "f",
      "comment": null,
      "traditional": false,
      "project": false,
      "rating": 5,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "p/gallery/aq4cmtyq.png",
      "userName": "Jeremy Abraham",
      "userSlug": "jeremy-abraham",
      "date": "2019-10-09T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": true,
      "isSoft": false,
      "type": "rp",
      "comment": "Fucking Nemesis Rig. Finally done. Feel like I'm on the edge of a new level for me. Big up to Max G for being my good luck charm",
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Abe Rifkin",
      "userSlug": "abe-rifkin",
      "date": "2019-08-16T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "",
      "traditional": false,
      "project": false,
      "rating": 5,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": true,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": true,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": true,
      "isCrimpy": true,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": true,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "p/gallery/jrsr3ecx.jpg",
      "userName": "Jon Schleicher",
      "userSlug": "jon-schleicher",
      "date": "2019-06-19T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "Very long boulder, fun movement in the crux. A bit sharp in some places though",
      "traditional": false,
      "project": false,
      "rating": 3,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Mark Springer",
      "userSlug": "mark-springer",
      "date": "2019-06-09T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": null,
      "traditional": false,
      "project": false,
      "rating": 5,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": true,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "gallery/27101.jpg",
      "userName": "Emily Dusatko",
      "userSlug": "emily-dudley",
      "date": "2019-05-31T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "Fun and long traverse. A tad sharp but it climbs well, very enjoyable.",
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "p/gallery/5piwqjnq.jpg",
      "userName": "Remington J. Vanderbilt",
      "userSlug": "remington-jeffrey-vanderbilt-iv",
      "date": "2019-05-27T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": true,
      "type": "rp",
      "comment": null,
      "traditional": false,
      "project": false,
      "rating": 3,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": true,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "",
      "userName": "Anonymous",
      "userSlug": "",
      "date": "2019-05-26T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "",
      "traditional": false,
      "project": false,
      "rating": 1,
      "userPrivate": true,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "gallery/8311.jpg",
      "userName": "Nina Williams",
      "userSlug": "nina-williams-f",
      "date": "2019-05-21T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "f",
      "comment": "numbed tf out but held on anyways!",
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Ben Vernon",
      "userSlug": "ben-vernon",
      "date": "2019-05-18T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": true,
      "type": "rp",
      "comment": null,
      "traditional": false,
      "project": false,
      "rating": 3,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "p/gallery/nqzcywhm.jpg",
      "userName": "Isabelle Gibbs",
      "userSlug": "isabelle-gibbs-vqo12",
      "date": "2019-05-15T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "bouldering outdoors = hard ,,, next??",
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "p/gallery/ivm5t0qd.jpg",
      "userName": "Ameen Hosain",
      "userSlug": "ameen-hosain",
      "date": "2019-05-14T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "f",
      "comment": "Amazing boulder",
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "p/gallery/fxpy2mhb.png",
      "userName": "Christian Wagner",
      "userSlug": "christian-wagner",
      "date": "2019-05-12T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": null,
      "traditional": false,
      "project": false,
      "rating": 3,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "p/gallery/20trbtpq.jpg",
      "userName": "Walker Emerson",
      "userSlug": "walker-emerson",
      "date": "2019-05-11T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "f",
      "comment": null,
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Rob D'Anastasio",
      "userSlug": "rob-danastasio",
      "date": "2019-05-11T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": null,
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Jessica Branchizio",
      "userSlug": "jessica-branchizio",
      "date": "2019-04-23T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "My favorite climb in the front range so far! The ending is not a give me!",
      "traditional": false,
      "project": false,
      "rating": 5,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Louie Stewart",
      "userSlug": "louie-stewart",
      "date": "2019-04-02T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": null,
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Spiggy G",
      "userSlug": "eddie-marovich",
      "date": "2019-03-17T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "First day out in what feels like forever. Felt good to be hangin in the sun and climbing in the shade",
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "gallery/25966.jpg",
      "userName": "Edwin Teran",
      "userSlug": "edwin-teran",
      "date": "2019-03-14T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "Surprisingly really good.  First time bouldering in clear creek.",
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "John Thomas",
      "userSlug": "john-thomas",
      "date": "2019-03-10T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "excellent! Wish I got on this years ago",
      "traditional": false,
      "project": false,
      "rating": 5,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "p/gallery/dt3f0nni.jpg",
      "userName": "Randy Martin",
      "userSlug": "randy-martin",
      "date": "2019-03-09T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": null,
      "traditional": false,
      "project": false,
      "rating": 3,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Ben Cooper",
      "userSlug": "ben-cooper",
      "date": "2019-01-28T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "Srsly ate shit in the rocks after vry nice dry fire",
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "gallery/50912.png",
      "userName": "Juliet Hammer",
      "userSlug": "juliet-hammer",
      "date": "2018-12-31T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": null,
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "gallery/42122.jpg",
      "userName": "Fanny Dong",
      "userSlug": "fanny-dong",
      "date": "2018-12-01T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "Too cold to climb this many moves. Would almost (but still not) be cool if there weren't a million better easier exits you could take.",
      "traditional": false,
      "project": false,
      "rating": 1,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Sam Sommers",
      "userSlug": "sam-sommers",
      "date": "2018-03-17T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "f",
      "comment": null,
      "traditional": false,
      "project": false,
      "rating": 3,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": "",
      "userName": "Anonymous",
      "userSlug": "",
      "date": "2017-11-11T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "",
      "traditional": false,
      "project": false,
      "rating": 3,
      "userPrivate": true,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": true,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    },
    {
      "userAvatar": null,
      "userName": "Craig Faulhaber",
      "userSlug": "craig-faulhaber",
      "date": "2016-11-13T00:00:00+00:00",
      "difficulty": "7A+",
      "isHard": false,
      "isSoft": false,
      "type": "rp",
      "comment": "",
      "traditional": false,
      "project": false,
      "rating": 0,
      "userPrivate": false,
      "zlagGradeIndex": 24,
      "zlaggableName": "Into the Light",
      "zlaggableSlug": "into-the-light",
      "cragSlug": "cat-slab-boulders",
      "cragName": "Cat Slab Boulders",
      "countrySlug": "united-states",
      "countryName": "United States",
      "areaSlug": "clear-creek-canyon-co",
      "areaName": "Clear Creek Canyon (CO)",
      "sectorSlug": "unknown-sector",
      "sectorName": "Unknown Sector",
      "category": 1,
      "recommended": false,
      "firstAscent": false,
      "secondGo": false,
      "isBoltedByMe": false,
      "isOverhang": false,
      "isVertical": false,
      "isSlab": false,
      "isRoof": false,
      "isAthletic": false,
      "isEndurance": false,
      "isCrimpy": false,
      "isCruxy": false,
      "isSloper": false,
      "isTechnical": false,
      "isDanger": false,
      "chipped": false,
      "badAnchor": false,
      "badBolts": false,
      "highFirstBolt": false,
      "looseRock": false,
      "badClippingPosition": false
    }
  ]
};

(async function() {
  const result = format(INPUT);
  console.log(JSON.stringify(result, null, 2));
})()